import { IMovieDataProps } from "@/interface/globalTypes";
 
export const movieDataHelpers: IMovieDataProps[] = [
        {
            id: 1,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 2,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 3,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 4,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 5,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 6,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 7,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 8,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 9,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 10,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 11,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 12,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 13,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 14,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 15,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 16,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 17,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 18,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 19,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 20,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 21,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 22,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 23,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 24,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 25,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 26,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 27,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 28,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 29,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 30,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 31,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 32,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 33,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 34,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 35,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 36,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 37,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 38,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 39,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 40,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 41,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 42,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 43,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 44,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 45,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 46,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 47,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 48,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 49,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 50,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 50,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 51,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 52,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 53,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 54,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 55,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 56,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 57,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 58,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 59,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 60,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
  ];
  