import { IMovieDataProps } from "@/interface/globalTypes";
 
export const movieDataHelpers: IMovieDataProps[] = [
        {
            id: 1,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 2,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 3,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 4,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 5,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 6,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 7,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 8,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 9,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 10,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 11,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 12,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 13,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 14,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 15,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 16,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 17,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 18,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 19,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 20,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
  ];
  