import { IMovieDataProps } from "@/interface/globalTypes";

const today = new Date().toISOString();
const lastWeek = new Date(new Date().setDate(new Date().getDate() - 6)).toISOString();

export const movieDataHelpers: IMovieDataProps[] = [
        {
            id: 1,
            views: 10000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 2,
            views: 20000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
              "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
          },
        {
            id: 3,
            views: 8000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 4,
            views: 9000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 5,
            views: 7000,
            lastViewed: today,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 6,
            views: 5000,
            lastViewed: today,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 7,
            views: 2000,
            lastViewed: today,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 8,
            views: 11000,
            lastViewed: today,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 9,
            views: 15000,
            lastViewed: today,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 10,
            views: 20000,
            lastViewed: today,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 11,
            views: 12000,
            lastViewed: today,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 12,
            views: 16000,
            lastViewed: today,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 13,
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
            views: 2000,
            lastViewed: today,
        },
        {
            id: 14,
            views: 4000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 15,
            views: 6000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 16,
            views: 3200,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 17,
            views: 7000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 18,
            views: 5000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 19,
            views: 2000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 20,
            views: 100,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 21,
            views: 1000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 22,
            views: 900,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 23,
            views: 8000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 24,
            views: 1000,
            lastViewed: today,
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 25,
            views: 2000,
            lastViewed: today,
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 26,
            views: 6000,
            lastViewed: lastWeek, 
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 27,
            views: 9000,
            lastViewed: lastWeek, 
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 28,
            views: 8000,
            lastViewed: lastWeek, 
            section: 'Animes',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 29,
            views: 12000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 30,
            views: 10000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 31,
            views: 7000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 32,
            views: 5000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 33,
            views: 6000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 34,
            views: 1000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 35,
            views: 900,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 36,
            views: 700,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 37,
            views: 200,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 38,
            views: 11000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 39,
            views: 12000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 40,
            views: 10300,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 41,
            views: 23000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 42,
            views: 22000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 43,
            views: 22000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 44,
            views: 29000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 45,
            views: 27000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 46,
            views: 22000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 47,
            views: 21000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 48,
            views: 10000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 49,
            views: 900,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 50,
            views: 10100,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 51,
            views: 14000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 52,
            views: 15000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 53,
            views: 16000,
            lastViewed: lastWeek, 
            section: 'Series',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 54,
            views: 17000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 55,
            views: 17000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 56,
            views: 19000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 57,
            views: 2000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            director: "James Gunn",
            duration: "2h 16min",
            genre: ["Action", "Adventure", "Comedy"],
            rate: '7.7',
            poster:
                "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        },
        {
            id: 58,
            views: 12000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            director: "George Lucas",
            duration: "2h 1min",
            genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
            rate: '8.7',
            poster:
            "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
        },
        {
            id: 59,
            views: 22000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
        {
            id: 60,
            views: 3000,
            lastViewed: lastWeek, 
            section: 'Movies',
            review: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
            title: "The Lord of the Rings: The Fellowship of the Ring",
            year: 2001,
            director: "Peter Jackson",
            duration: "2h 58min",
            genre: ["Action", "Adventure", "Drama", "Fantasy"],
            rate: '8.8',
            poster:
                "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
        },
  ];
  